# Generated by Django 5.1.2 on 2024-10-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Rakib', max_length=100),
        ),
    ]
