# Generated by Django 5.1.2 on 2024-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_student_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='sections', max_length=100),
        ),
    ]
