# Generated by Django 5.1.2 on 2024-10-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(default='Rakib', max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
